### ISSUE TITLE
Improve the exercise

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m1-evaluacion-intermedia-superanika#1]
Really cool job @superanika!!!

Here you have some tips to improve the exercise:

- [x] Fix the language and the meta title of the page
- [x] Humanize text in `alt` attributes, a sentence describing the linked image may do the trick.
- [x] Class selectors are free, let's use them instead tag selectors 
- [x] Avoid uppercase/capital on HTML texts, and `br` tag we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles

Let me know if you have any doubts ;)

Go for it!!

**Comment by oneeyedman** [comment]
Good Job @superanika!

I left one checkbox unchecked because of the `li` selector that remains in the stylesheet.

**Comment by superanika** [comment]
done! 🌈
